name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t botarena .

    - name: Run tests
      run: docker run --rm -v ${{ github.workspace }}:/app botarena cargo test --release
